### ISSUE TITLE
Product thumbnail support in email templates

### ISSUE THREAD

**Issue by bystro** [shopware/shopware#1036] opened 2020-06-16 13:15 UTC
**Description**  
Possibility of having thumbnails of products in emails are being sent by a platform.

**Example** 
Table with ordered products in order confirmation email could looked like below
<img width="843" alt="obraz" src="https://user-images.githubusercontent.com/14996446/84779269-7a734380-afe4-11ea-93a7-2d2298bb084c.png">

**Comment by keulinho** [comment] 2023-03-02 13:28
Seems to be a duplicate of [this ticket](https://issues.shopware.com/issues/NEXT-23943).

I'll close this issue for now, please follow the status in the linked issue.

**Closed as completed by keulinho** 2023-03-02 13:28 UTC
