### ISSUE TITLE
Sorting of custom fields is not numeric

### ISSUE THREAD

**Issue by htuscher** [shopware/shopware#1106] opened 2020-07-07 08:34 UTC
**Description**  
When having more than 9 custom fields in a set, the sorting is incorrect.

![image](https://user-images.githubusercontent.com/5076356/86749225-5cc25880-c03d-11ea-8e5c-1994c3f86b53.png)

It seems that the sorting is in lexicographic order but should be in numerical order.

**Comment by JoshuaBehrens** [comment] 2020-07-07 08:52
I already looked into it once. AFAIK the problem is the administration and not the DAL. The DAL is querying and returning the sorting correctly but merging it into a EntityCollection in admin js makes it sorting like this. These are my last debugging notes on this.

I still have this SQL snippet saved but I am not sure why 🙈 
```
IF(JSON_TYPE(JSON_EXTRACT(`custom_field`.`config`, '$.customFieldPosition')) != "NULL", CONVERT(JSON_UNQUOTE(JSON_EXTRACT(`custom_field`.`config`, '$.customFieldPosition')) USING "utf8mb4") COLLATE utf8mb4_unicode_ci, NULL)
```

**Comment by keulinho** [comment] 2023-03-02 13:34
Should have been fixed in https://github.com/shopware/platform/pull/599

**Closed as completed by keulinho** 2023-03-02 13:34 UTC
