### ISSUE TITLE
UUIDs in full format (with hyphens) are considered as invalid in Shopware REST API

### ISSUE THREAD

**Issue by patpilus** [shopware/shopware#274] opened 2019-11-04 14:06 UTC
**Description**  
Whenever I'm trying to pass UUID v4 in full format (with hyphens, eg. `deb6bccd-11de-4c01-9046-73354df7f004` via REST API, Shopware responses with `FRAMEWORK__INVALID_UUID` error: 
`Value is not a valid UUID: deb6bccd-11de-4c01-9046-73354df7f004`

```
       {
		"status": "400",
		"code": "FRAMEWORK__INVALID_UUID",
		"title": "Bad Request",
		"detail": "Value is not a valid UUID: deb6bccd-11de-4c01-9046-73354df7f004",
		"meta": {
			"parameters": {
				"input": "deb6bccd-11de-4c01-9046-73354df7f004"
			}
		}
	}
```

**Possible Solution**  
Accept UUIDs both with and without hyphens according to RFC: https://tools.ietf.org/html/rfc4122

**Comment by keulinho** [comment] 2019-11-04 14:19
Hey @patpilus 

thanks for raising this issue.
In fact this is the expected behaviour, as we allowed UUIDs with hyphens before.
You can see the update post: here https://docs.shopware.com/en/shopware-platform-dev-en/getting-started/recent-updates#2019-07-05-uuid-format-change 
(the layout of the recent updates seems broken atm)

The reason for disallowing dashed UUIDs is that the server would convert the UUID and strip the hiphens wich leads to problems because the UUID of the request (with hyphens) may change from the UUID from the response (where the hyphens are stripped).

Because of this incontencies we decided to not support UUIDs with hyphens.

I will be closing this for now, if you think we should reconsider this decision and have a few arguments for it or if you have any furhter questions, don't hesitate reopening this issue.

Kind regards
Jonas

**Closed as completed by keulinho** 2019-11-04 14:19 UTC

**Comment by pawonpawon** [comment] 2020-05-15 10:41
At least this should be updated in the DOCS here: https://docs.shopware.com/en/shopware-platform-dev-en/admin-api-guide/writing-entities?category=shopware-platform-dev-en/admin-api-guide

Since the UUIDv4 specs are specifically using hyphens, and all UUIDv4 generators and libraries only generate UUIDs with hyphens we can not expect new users to just know this - cost me 2 hours of my life.

**Comment by UlrichThomasGabor** [comment] 2020-09-09 11:26
This is really unexpected.

**Comment by renickbuettner** [comment] 2022-02-01 20:20
.__.

**Comment by SkaveRat** [comment] 2023-01-20 12:37
Would be great to at least allow it in *some* capacity.

I'm currently migrating data from another shop system, which also uses UUIDs. The exported data is all formatted with dashes, so now I need to strip them everywhere I want to keep the original ID, instead of just using the data as-is.

The more annoying part is, that large parts of the Migration Assistant code will happily use the dashes version, but only complain when it wants to write it to the DB as an ID
