### ISSUE TITLE
Syncapi fatal error if visibilities already present

### ISSUE THREAD

**Issue by ascheider** [shopware/shopware#595] opened 2020-02-28 11:18 UTC
**Shopware Version: v6.1.3 Stable Version**
**Description:**  
If i try to sync a shopware product with the sync api, i get the 500 error if visibilities are already present in the database. So the second upsert of the product always fail because shopware is trying to insert the item instead of ignore it.
![image](https://user-images.githubusercontent.com/6016485/75544205-c8f3d680-5a23-11ea-87c6-3b1608fce35d.png)

1. Expected behaviour:
Pass visibilities with product upsert. If visibilities are present, ignore insert.

2. Actual behaviour:
First sync is successfully if no product present in shopware. Second sync fails, because visibilities already created. This should not be the case on upsert.

**Comment by alexschwarz89** [comment] 2021-02-09 07:00
Also an issue if using repository directly in 6.3.4.1, push

**Comment by StevendeVries** [comment] 2021-08-02 10:13
Isn't this expected behavior? Since you aren't adding id's to the visibilities it will try to insert and fail. In the second call you would have to search the visibilities and add the id's to it (or simply remove them and force the insert).

**Comment by digitalkaoz** [comment] 2022-02-08 10:05
@StevendeVries no its not expected behavior, its an `UPSERT` request to the sync api, which means update OR create the visibility (since we cant know the visibilityId if its already existing)

**Comment by digitalkaoz** [comment] 2022-02-08 10:19
for us its a total showstopper (the same issues seems to appear for category upserts)- since that bug is nearly 1 year open, WTH? upserts seem to be broken.

**Comment by StevendeVries** [comment] 2022-02-08 16:49
@digitalkaoz Not saying I agree with the approach, but if you do an upsert without an identifier it is considered as an insert. The unique constraint will result in a failure. First you will have to search for the visibilities and add the appropriate identifiers, it will then resort to an update.

**Comment by digitalkaoz** [comment] 2022-02-08 16:51
@StevendeVries yeah well, then its not an upsert, in case of visibilities i guess its pretty easy to find by `salesChannelId` and `productId` and i would say it would be a pretty unique result. so still no, its broken.

**Comment by MarcelSchmaeing** [comment] 2024-08-20 08:13
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.

**Closed as not planned by MarcelSchmaeing** 2024-08-20 08:13 UTC
