### ISSUE TITLE
sw-url-field removes query parameters from the URL 

### ISSUE THREAD

**Issue by zaifastafa** [shopware/shopware#1254] opened 2020-08-19 12:52 UTC
**Description**  
As the title says, when using a url with query parameters, it removes the query parameters

**Possible Solution**  

**Additional context**  
For e.g this link
http://sw6.dev.localhost/rma/ticket/view?id=10046-13081374&hash=ad6cce345cb24137a63549caa3508973
when added to the sw-url-field, only shows 
![image](https://user-images.githubusercontent.com/24492269/90636754-84176280-e244-11ea-8e7b-7a067d988bab.png)

**Comment by dominikkremer** [comment] 2020-08-20 19:14
I checked the `sw-url-field` component and it seems to be working as intended.
The input field value is set like this `url.hostname + path`, the query parameters are simply ignored.

Path = `/rma/ticket/view`
Hostname = `sw6.dev.localhost`

I could imagine a solution which adds a prop as option to enable / disable parameters. 
Now a developer would be able to explicitly allow query parameters if required.

**Comment by MarcelSchmaeing** [comment] 2024-08-20 14:00
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.

**Closed as not planned by MarcelSchmaeing** 2024-08-20 14:00 UTC
