### ISSUE TITLE
6.3.2.0 - custom field values are being assigned to all categories

### ISSUE THREAD

**Issue by aayaresko** [shopware/shopware#1476] opened 2020-11-02 12:48 UTC
**Description**  
if we create a custom field, assign the field to categories. then, we set a value for the field in a category. we will see that the value will be set to all categories. 

**Possible Solution**  
it should not set the value for the field for all categories

**Additional context**  
the issue is related to 6.3.2.0 version specifically.

**Comment by FynnZW** [comment] 2020-12-03 11:24
I can confirm, but this seems to be a JS/Vue issue - the data does not actually get stored for all categories, but the form fields don't reset when switching to another category.
If the category that I'm switching too already has filled out values, it shows the correct values. If I switch to a new category with empty fields and do a hard refresh, I can also fill the fields normally, just switching without reloading breaks it (shows wrong values).

**Comment by aayaresko** [comment] 2020-12-11 08:10
yes, most likely it is a JS/Vue issue. I was wrong about the origins of it in my first post here. thanx for pointing that out.

> I can confirm, but this seems to be a JS/Vue issue

**Comment by mitelg** [comment] 2021-01-14 09:58
should be fixed with https://github.com/shopware/platform/pull/1566

**Closed as completed by mitelg** 2021-01-14 09:58 UTC
