### ISSUE TITLE
Redirect loop when changing e-mail during guest checkout

### ISSUE THREAD

**Issue by lars-feyerabend** [shopware/shopware#1452] opened 2020-10-26 09:20 UTC
**Description**  

Steps to reproduce:
- Put random item into cart
- Start checkout
- Choose guest checkout on /checkout/register page
- On /checkout/confirm notice that your email address is wrong
- Click browser back button
- Change email in form
- Submit

Expected behaviour:
- A new guest account/session is created with the newly entered email and the customer is again on /checkout/confirm

Actual behaviour:
- A redirect loop occurs

**Possible Solution**  

My proposed solution to break this cycle would be to change the first check in `\Shopware\Storefront\Controller\RegisterController::register` as follows:

```php
if ($context->getCustomer() && !$context->getCustomer()->getGuest()) {
    return $this->redirectToRoute('frontend.account.home.page');
}
```

A more detailed look into the handling of the various steps with regards to guest account handling couldn't hurt though.

**Additional context**  

The redirect is triggered in `\Shopware\Storefront\Controller\RegisterController::register`, where `if ($context->getCustomer())` leads to a redirect to `frontend.account.home.page` regardless of whether it's a guest account or not. `\Shopware\Storefront\Controller\AccountProfileController::index`(the target action) however starts with `$this->denyAccessUnlessLoggedIn();` (default parameter `$allowGuest = false`), which redirects to the Login page, but `\Shopware\Storefront\Controller\AuthController::loginPage` again only checks for `if ($context->getCustomer())` and redirects back to the account page - the endless loop begins. (The redirectTo parameter of the login page is set to the account page when the `\Shopware\Core\Checkout\Cart\Exception\CustomerNotLoggedInException` is handled in `\Shopware\Storefront\Framework\Routing\StorefrontSubscriber::customerNotLoggedInHandler`)

**Comment by lars-feyerabend** [comment] 2020-11-03 07:15
Added in Shopware issue tracker: https://issues.shopware.com/issues/NEXT-11790

**Comment by lernhart** [comment] 2021-12-03 10:23
Hey @lars-feyerabend, thank you for reporting this, and sorry for the late response. 
I'm closing this issue, as this landed in our triage and we can not reproduce this on current shopware release.

**Closed as completed by lernhart** 2021-12-03 10:23 UTC

**Comment by mstegmeyer** [comment] 2021-12-03 10:24
This issue has since been fixed by Shopware. https://issues.shopware.com/issues/NEXT-17938
