### ISSUE TITLE
Bug with minOrderQty + Prices

### ISSUE THREAD

**Issue by tinect** [shopware/shopware#746] opened 2020-04-14 10:40 UTC
**Description**  
We have prices (rules) beginning with 50.
This result in an error in storefront: 
![image](https://user-images.githubusercontent.com/135993/79216001-bc4d0580-7e4c-11ea-86b5-784fe4203031.png)

Problem: the prices is still collected with quantity of 1, no matter what MinOrderQuantity is definied or where the prices are starting.

**Possible Solution**  

**Additional context**

**Comment by rohithmeethal** [comment] 2020-04-14 19:17
This might be the same as this issue https://github.com/shopware/platform/issues/562 , Please vote the shopware issue to get it fixed :)

**Comment by pantrtxp** [comment] 2020-05-08 08:15
Duplicate of #562

**Closed as completed by pantrtxp** 2020-05-08 08:15 UTC
