### ISSUE TITLE
Categories not redirecting on missing slash

### ISSUE THREAD

**Issue by Zyles** [shopware/shopware#468] opened 2020-01-26 15:29 UTC
**Description**  

Slash and no slash at the end of an URL are two unique URLs according to Google.

```
https://www.shopwaredemo.co.uk/cooking-pleasure-provence/eat/fish
https://www.shopwaredemo.co.uk/cooking-pleasure-provence/eat/fish/
```

Are not the same page: https://webmasters.googleblog.com/2010/04/to-slash-or-not-to-slash.html

This leads to duplicate content issues.

There is also not a proper canonical tag on the page:
`<link rel="canonical" href="https://www.shopwaredemo.co.uk/" />`

Is not correct. Should be:
`<link rel="canonical" href="https://www.shopwaredemo.co.uk/cooking-pleasure-provence/eat/fish/" />`

**Possible Solution**  

301 redirect non-slash to slash for categories and pages.

Fix a proper canonical URL.

**Additional context**

**Comment by hlohaus** [comment] 2020-01-27 07:49
Yes, thats right. See my solution:
https://store.shopware.com/she8384344171469/ignoriere-trailing-slash-bei-seo-urls.html

**Comment by Zyles** [comment] 2020-01-27 11:49
I have to pay to fix a bug?

**Comment by Zyles** [comment] 2020-01-27 11:51
If you have solved it. Wouldn't it be better if you contributed to the open source project?

**Comment by hlohaus** [comment] 2020-01-28 07:24
i did it in sw5:
https://github.com/shopware/shopware/pull/2112

**Comment by pweyck** [comment] 2020-02-07 15:26
Hello @Zyles,

Sorry for the late response. Sadly I cannot reproduce your issues with the v6.1.1. By default, seo urls for categories are generated with a slash at the end and cannot be resolved without a slash. 

When I override it manually without a slash, both work and the response of the non-canonical contains the header: 

`Link: <http://docker.vm:8000/Foo/Bar>; rel="canonical"`

which is equivalent to the canonical tag. It should only be an issue if you rewrite the url on your web server/proxy before it reaches the app server. You could just use a redirect there. But I think we could also just always respond with the canonical link header to prevent this issue. I've created an issue in our issue tracker https://issues.shopware.com/issues/NEXT-6915.

Also, I cannot find the link tag with the canonical url of the home page. I think the demo shops were updated just recently. Maybe the old version had this bug.

**Comment by Zyles** [comment] 2020-02-07 15:45
So what version is www.shopwaredemo.co.uk using? I don't own it.

**Comment by hlohaus** [comment] 2020-02-08 12:16
it was sw5. :)
But maybe the config was not on.

**Comment by Zyles** [comment] 2020-02-09 17:59
I just tested an official demo store and no trailing slash results in a 404 when it should be 301 redirected.

Is there a setting?

**Comment by Zyles** [comment] 2020-02-09 18:01
Furthermore using a URL parameter `shopwaredemo.store/summer-bbq/?foobar=foo`

There is no canonical link in the source. This will make that page unique in Googles eyes.

And is a huge problem when using tracking codes for Google Ads, analytics etc.

**Comment by hlohaus** [comment] 2020-02-18 08:16
There is header with the canonical  url.

**Comment by Zyles** [comment] 2020-02-18 14:57
> There is header with the canonical url.

Not correct.

https://mydemoshopp.shopwaredemo.store/summer-bbq/grills/
https://mydemoshopp.shopwaredemo.store/summer-bbq/grills

https://mydemoshopp.shopwaredemo.store/cooking-pleasure-provence/?no-aggregations=1&p=1&properties=3a1cc241cab9426ba119d1bfdad9698c&slots=6d9539f3d81b48aaa4a2455a9f70ea4c&sort=name-asc
https://mydemoshopp.shopwaredemo.store/cooking-pleasure-provence?no-aggregations=1&p=1&properties=3a1cc241cab9426ba119d1bfdad9698c&slots=6d9539f3d81b48aaa4a2455a9f70ea4c&sort=name-asc

https://mydemoshopp.shopwaredemo.store/information/agb/
https://mydemoshopp.shopwaredemo.store/information/agb

**Comment by pweyck** [comment] 2020-02-21 10:16
Thanks for providing us with additional information @Zyles :+1: 

> Furthermore using a URL parameter `shopwaredemo.store/summer-bbq/?foobar=foo`
> 
> There is no canonical link in the source. This will make that page unique in Googles eyes.
> 
> And is a huge problem when using tracking codes for Google Ads, analytics etc.

As far as I know, you cannot simply strip all parameters and let them point to the first/root page. At least each page of the listing should be indexed separately. But we should normalize the urls with decent defaults and make the relevant parameters configurable.

**Comment by Zyles** [comment] 2020-02-21 21:24
it is actually best practice to strip the filtering and point to the root category. You should NOT index them separately.

Why?

Because it would create duplicate content to index the filters individually.

A category usually have text descriptions in it. If you filter it will have a mutation of the same content on another URL and create duplicated content.


It should work like this:
```
https://mydemoshopp.shopwaredemo.store/cooking-pleasure-provence/?no-aggregations=1&p=1&sort=name-asc

Canonical:
https://mydemoshopp.shopwaredemo.store/cooking-pleasure-provence/
```

The only thing that differes from page 1 and 2 are the products. Those should be indexed using sitemaps.

A category description / page is there to rank on generic keywords such as "cooking ware". If you have 10 pages of cooking ware with the exact same duplicate content. Google will not know what page you want to rank.

Creating a unique indexed url for every page in pagination does not help rankings, it hurts them.

**Comment by MarcelSchmaeing** [comment] 2024-08-20 14:06
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.

**Closed as not planned by MarcelSchmaeing** 2024-08-20 14:06 UTC
