### ISSUE TITLE
Contact form error

### ISSUE THREAD

**Issue by jd297** [shopware/shopware#449] opened 2020-01-20 10:59 UTC
**Description**  
When you submit a contact formular with all required data, you still get some alert messages with "This value should not be blank." four times.

**Additional context**  
![not be blank](https://user-images.githubusercontent.com/56673596/72721272-f2475a00-3b7b-11ea-9f85-8478d8f9f566.PNG)

Tested in Shopware 6.1 with different browsers on Win10

**Comment by taltholtmann** [comment] 2020-01-22 08:05
Hello @JD297,

i am not able to reproduce the issue in the 6.1 branch. Did you use the 6.1 release? If so, this issue should be fixes with the next patch release.

Sunny regards, 
Timo

**Comment by rammnco** [comment] 2020-01-27 21:24
Error still occurs with 6.1.1, for me at least. Can anyone confirm?

**Comment by jd297** [comment] 2020-01-27 21:45
@taltholtmann I tested it with 6.1.0 Stable Version. I have tried to find the bug. I can't tell you exactly where it is but I think it is a violation fail in the ContactFormService
Line 81: $this->validateContactForm($data, $context);

For some reason this returns the error but I don't know why.

**Comment by taltholtmann** [comment] 2020-02-26 10:22
Hey guys, 
is this still an issue, or can I close this case?

**Comment by rammnco** [comment] 2020-02-27 19:54
Just did the update to v6.1.3 and the issue is gone.

**Comment by jd297** [comment] 2020-02-27 20:44
Hey, I will check it tomorrow.


Nico Ramm <notifications@github.com> schrieb am Do., 27. Feb. 2020, 20:54:

**Closed as completed** 2020-05-05 06:50 UTC
