### ISSUE TITLE
Manage private media

### ISSUE THREAD

**Issue by FalkoHilbert** [shopware/shopware#938] opened 2020-05-15 10:51 UTC
**Description**  
Currently it is not really possible to upload or manage private media using the standard components.
Specifically, I would like to add private media via a plugin and also see and delete them in the media management. However, this is only partially possible through difficult detours and overloading of many locations.

**Possible Solution**  
- remove Scope filter at
  * https://github.com/shopware/platform/blob/6.2/src/Core/Content/Media/DataAbstractionLayer/MediaFolderRepositoryDecorator.php#L59-L65
  * https://github.com/shopware/platform/blob/6.2/src/Core/Content/Media/DataAbstractionLayer/MediaFolderRepositoryDecorator.php#L78-L85
  * https://github.com/shopware/platform/blob/6.2/src/Core/Content/Media/DataAbstractionLayer/MediaRepositoryDecorator.php#L102-L104
  * https://github.com/shopware/platform/blob/6.2/src/Core/Content/Media/DataAbstractionLayer/MediaRepositoryDecorator.php#L116-L118
- remove `private`-conditions in https://github.com/shopware/platform/blob/6.2/src/Administration/Resources/app/administration/src/app/component/media/sw-media-media-item/sw-media-media-item.html.twig

**Additional context**

**Comment by mitelg** [comment] 2020-05-20 06:12
afaik, it is not intended by design that private files are manageable via the admin media module. I think they are supposed to be managed by the plugin or module which created them and not by the shop manager. Imagine a plugin which creates labels for shipping and the shop manager can delete and change as he/she wants. 
So basically the private file system should be handled by code and not a user. 
Question is, why do the files have to be in the private file system, if they can be managed by the shop manager anyway?

**Comment by FalkoHilbert** [comment] 2020-05-20 06:57
The files should be in a private directory so that they cannot be accessed from outside, but the shop manager should be able to manage them.

**Comment by MarcelSchmaeing** [comment] 2024-08-20 14:03
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.

**Closed as not planned by MarcelSchmaeing** 2024-08-20 14:03 UTC
