### ISSUE TITLE
basic auth not working for /admin

### ISSUE THREAD

**Issue by ieslei** [shopware/shopware#106] opened 2019-06-03 15:21 UTC
Hi,

I am trying to add basic auth in the apache config, it works in the frontend, but in admin there are lots of 401 error, like this one below
`{"errors":[{"code":"9","status":"401","title":"The resource owner or authorization server denied the request.","detail":"The JWT string must have two dots"}]}`
for requests like `api/v1/language/2fbb5fe2e29a4d70aa5854ce7ce3e20b`

here is my apache config
```
    AllowOverride All
    Options Indexes FollowSymLinks MultiViews

    AuthType Basic
    AuthName "Restricted Area"
    AuthBasicProvider file
    AuthUserFile "/var/www/.htpasswd"
    Require valid-user
```

is there some workaround here, or something wrong in my config?

Lei

**Comment by klarstil** [comment] 2019-08-06 11:22
This seems like an actual issue which I can reproduce. I added the necessary information to the `.htaccess` file inside the `/public` folder. The initial load looks good but every API requests returns a 401 HTTP Unauthorized error. The Response body looks like this:

```
{"errors":[{"code":"9","status":"401","title":"The resource owner or authorization server denied the request.","detail":"The JWT string must have two dots"}]}
```

@janbuecker Can you take care of this issue? It seems like the appropriate auth header gets dropped.

**Comment by janbuecker** [comment] 2019-08-06 13:18
We are using the `Authorization` for the bearer token, but the htaccess file uses basic auth. We have to think about how we accomplish this. I guess this is not an easy task, but we do have an [issue ticket](https://issues.shopware.com/issues/NEXT-4243) for that.

**Comment by klarstil** [comment] 2019-08-13 11:31
I'm closing this ticket on here for now. The issue ticket has been created our internal systems and will be taken care of shortly. Thank you all for your contributions and the great feedback.

**Closed as completed by klarstil** 2019-08-13 11:31 UTC

**Comment by opctim** [comment] 2026-03-18 09:20
That ticket is almost 6 years old and the issue still persists.

Any progress in sight?
