### ISSUE TITLE
api 412 errors in firefox

### ISSUE THREAD

**Issue by lordofthebrain** [shopware/shopware#110] opened 2019-07-31 12:56 UTC
Hello,

the administration area don't run correctly in firefox. No orders, products,. ...
Symfony Profiler shows many 412 http errors.

**Comment by klarstil** [comment] 2019-08-06 07:02
Hey @lordofthebrain 

thanks for your issue. I double checked the behavior you described here and wasn't able to reproduce it in Firefox 68.0.1 (64-Bit) as well as Firefox Nightly 67.0a1 (2019-03-08) (64-bit) and Firefox Developer Edition 65.0b4 (64-Bit).

Can you provide us with more information about the issue?

**Comment by klarstil** [comment] 2019-08-13 08:11
I'm closing this issue because it has not had recent activity. Thank you for your contribution. If the issue still exists, feel free to open a new issue please.

**Closed as completed by klarstil** 2019-08-13 08:11 UTC

**Comment by patchee500** [comment] 2020-01-09 20:04
I just came across this issue. The issue is not limited to Firefox.  
For me it happened in Chrome.  

A solution is described here: https://forum.shopware.com/discussion/comment/255437/#Comment_255437

Simply adding another language in the admin panel (doesn't matter which one, it can be deleted afterwards again) restores the backend.  

Maybe somehow through upgrading (at least that's what I did) or something the language of the backend/user is getting lost which in return produces the error.

The following stack trace is the response body that came by requesting http://localhost:8000/api/v1/language/2ad5b2587ae24c87ad09b454c57320a5
```
{"errors":[{"code":"9","status":"401","title":"The resource owner or authorization server denied the request.","detail":"Missing \u0022Authorization\u0022 header","meta":{"trace":[{"file":"\/app\/vendor\/league\/oauth2-server\/src\/AuthorizationValidators\/BearerTokenValidator.php","line":62,"function":"accessDenied","class":"League\\OAuth2\\Server\\Exception\\OAuthServerException","type":"::","args":["Missing \u0022Authorization\u0022 header"]},{"file":"\/app\/vendor\/league\/oauth2-server\/src\/ResourceServer.php","line":84,"function":"validateAuthorization","class":"League\\OAuth2\\Server\\AuthorizationValidators\\BearerTokenValidator","type":"-\u003E","args":[{}]},{"file":"\/app\/vendor\/shopware\/platform\/src\/Core\/Framework\/Api\/EventListener\/Authentication\/ApiAuthenticationListener.php","line":117,"function":"validateAuthenticatedRequest","class":"League\\OAuth2\\Server\\ResourceServer","type":"-\u003E","args":[{}]},{"file":"\/app\/vendor\/symfony\/event-dispatcher\/Debug\/WrappedListener.php","line":126,"function":"validateRequest","class":"Shopware\\Core\\Framework\\Api\\EventListener\\Authentication\\ApiAuthenticationListener","type":"-\u003E","args":[{},"kernel.controller",{}]},{"file":"\/app\/vendor\/symfony\/event-dispatcher\/EventDispatcher.php","line":264,"function":"__invoke","class":"Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener","type":"-\u003E","args":[{},"kernel.controller",{}]},{"file":"\/app\/vendor\/symfony\/event-dispatcher\/EventDispatcher.php","line":239,"function":"doDispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"-\u003E","args":[[{},{},{},{},{},{},{},{},{},{},{},{},{}],"kernel.controller",{}]},{"file":"\/app\/vendor\/symfony\/event-dispatcher\/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"-\u003E","args":[[{},{},{},{},{},{},{},{},{},{},{},{},{}],"kernel.controller",{}]},{"file":"\/app\/vendor\/shopware\/platform\/src\/Core\/Framework\/Event\/BusinessEventDispatcher.php","line":43,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"-\u003E","args":[{},"kernel.controller"]},{"file":"\/app\/vendor\/shopware\/platform\/src\/Core\/Framework\/Event\/NestedEventDispatcher.php","line":32,"function":"dispatch","class":"Shopware\\Core\\Framework\\Event\\BusinessEventDispatcher","type":"-\u003E","args":[{},"kernel.controller"]},{"file":"\/app\/vendor\/symfony\/event-dispatcher\/Debug\/TraceableEventDispatcher.php","line":168,"function":"dispatch","class":"Shopware\\Core\\Framework\\Event\\NestedEventDispatcher","type":"-\u003E","args":[{},"kernel.controller"]},{"file":"\/app\/vendor\/symfony\/http-kernel\/HttpKernel.php","line":134,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher","type":"-\u003E","args":[{},"kernel.controller"]},{"file":"\/app\/vendor\/symfony\/http-kernel\/HttpKernel.php","line":68,"function":"handleRaw","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"-\u003E","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}},1]},{"file":"\/app\/vendor\/symfony\/http-kernel\/Kernel.php","line":201,"function":"handle","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"-\u003E","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}},1,true]},{"file":"\/app\/vendor\/shopware\/platform\/src\/Core\/HttpKernel.php","line":148,"function":"handle","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"-\u003E","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}},1,true]},{"file":"\/app\/vendor\/shopware\/platform\/src\/Core\/HttpKernel.php","line":77,"function":"doHandle","class":"Shopware\\Core\\HttpKernel","type":"-\u003E","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}},1,true]},{"file":"\/app\/public\/index.php","line":47,"function":"handle","class":"Shopware\\Core\\HttpKernel","type":"-\u003E","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]}],"file":"\/app\/vendor\/league\/oauth2-server\/src\/Exception\/OAuthServerException.php","line":223}}]}
```
This would suggest it's somewhat related to permissions.
