### ISSUE TITLE
Shopware 6 docker installation failed  @26/37

### ISSUE THREAD

**Issue by LighthouseIVM** [shopware/shopware#105] opened 2019-07-26 13:20 UTC
Hello, 

we tried to install shopware 6 on a vm(CentOS 7) via docker but we keep getting the same error over and over again. 
after connecting to docker with ssh we tried "./psh.phar install" but it always crashes @(26/37) and we have no clue why. 
We tried different workarounds etc. but we still didn't manage to make it work properly. 
Sometimes the installation would run through but we don't know why and we were not able to reproduce it. 

There were many different errors for example something like :
" 
        events.js:170
              throw er; // Unhandled 'error' event
              ^

        Error: ENOENT: no such file or directory, open '/app/platform/src/Administration/Resources/public/static/js/storefront.js'
        Emitted 'error' event at:
            at /app/platform/src/Administration/Resources/common/webpack-plugin-injector/node_modules/graceful-fs/graceful-fs.js:207:14
            at /app/platform/src/Administration/Resources/common/webpack-plugin-injector/node_modules/graceful-fs/graceful-fs.js:258:16
            at FSReqCallback.args [as oncomplete] (fs.js:145:20)
        npm ERR! code ELIFECYCLE
        npm ERR! errno 1
        npm ERR! administration@1.0.0 build: `node build/build.js`
        npm ERR! Exit status 1
        npm ERR!
        npm ERR! Failed at the administration@1.0.0 build script.
        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

        npm ERR! A complete log of this run can be found in:
        npm ERR!     /.npm/_logs/2019-07-26T08_59_20_919Z-debug.log

Execution aborted, a subcommand failenm! "

Has anyone experienced a similar if not the same issue ? 
Thanks in advance!

**Comment by janbuecker** [comment] 2019-07-30 07:58
Closing as a duplicate of #48

**Closed as completed by janbuecker** 2019-07-30 07:58 UTC
