### ISSUE TITLE
NEXT-8267 - Variants in the admin / price on discounts only partially visible

### ISSUE THREAD

**Issue by Phil23** [shopware/shopware#824] opened 2020-05-07 08:26 UTC
EN:
In the backend when creating variants, a maximum of 6 positions are displayed under "Price/ Surcharges/Discounts". It is not possible to scroll down to enter the markups

Environment: 6.1.5

Steps for reproduction: Create variants / enter markups / markdowns

Expected result: Display of all variants in the list under markups and markdowns

Actual result: max. 6 displayed variants

 

DE:
Im Backend beim Anlegen von Varianten werden maximal 6 Positionen unter "Preis/ Auf- Abschläge dargestellt. Es kann nicht weiter nach unten gescrollt werden um die Aufschläge einzutragen

Umgebung: 6.1.5

Schritte zur Reproduktion: Anlegen von Varianten / Auf- / Abschläge eintragen

Erwartetes Ergebnis: Darstellung aller Varianten in der Liste unter Auf-/Abschläge

Tatsächliches Ergebnis: max. 6 dargestellte Varianten

[Backend_Varianten.jpg](https://sbp-issuetracker-attachments.s3.eu-west-1.amazonaws.com/1587919293_5ea5b9bdd24a0_1587919260_5ea5b99c0f2fe_Backend_Varianten.jpg)

**Comment by wexojch** [comment] 2020-05-14 08:20
@Phil23 
It looks like it's fixed in the current version
![image](https://user-images.githubusercontent.com/65078828/81910065-c7ba5a80-95cb-11ea-93f2-94fda35c889b.png)

**Comment by mitelg** [comment] 2020-05-14 08:36
@wexojch would you like to post this in the QA channel? so they can double check and close the issue :+1:

**Comment by leichteckig** [comment] 2020-05-14 09:02
I double checked and can't reproduce it either. Only thing I saw is that the last entry is cut by the footer of the modal view, maybe it would be a quick pick to fix:
![grafik](https://user-images.githubusercontent.com/29896429/81914936-38647580-95d2-11ea-9439-e2a285f92d8d.png)

**Comment by tobiasberge** [comment] 2020-06-22 13:32
The missing scrollbar was already fixed and the issue with the cut off grid was resolved through this PR: https://github.com/shopware/platform/pull/923

**Closed as completed by tobiasberge** 2020-06-22 13:32 UTC
Labels: component/administration
