### ISSUE TITLE
Theme Config of a duplicated theme is not updated

### ISSUE THREAD

**Issue by NicoWenig27** [shopware/shopware#507] opened 2020-02-05 16:06 UTC
**Description**  
When I update my theme plugin to a new version where the theme.json has new fields, only the original theme config gets those new fields. Duplicated themes of the original won't get the new fields.

**Additional context**  
Steps to reproduce:

1. Create a new theme plugin with one custom field in the theme.json
2. Install and activate plugin
3. Duplicate the theme
4. Update the theme.json and add a new field
5. Compare the theme configs of the original and the duplicated theme

**Comment by ssltg** [comment] 2020-02-20 12:54
Hi @NicoWenig27 ,
your described behaviour works as intended. https://docs.shopware.com/en/shopware-platform-dev-en/internals/plugins/plugin-themes#inheritance-of-theme-config
A Duplicated Theme is actually a copy, not an inheritance when it comes to configuration. If you Update your ThemePlugin you have to create a new Duplication and then assign this to your Saleschannel.
This is done this way to minimize possible Breaks on running Storefronts.
We are aware of the need for a more convient way to make updates on duplications and there is a Ticket in our Issue Tracker vor this Topic: https://issues.shopware.com/issues/NEXT-6402

**Comment by NicoWenig27** [comment] 2020-02-21 15:32
Hi @ssltg,

thanks for the answer! My problem with this is, that when you have a duplicated theme for a sales channel with its own theme config and update the main theme, you have to duplicate it again and copy all config to the new duplicated theme. So yes, I think there should be a way to update duplicates, without creating a complete new one. 

I think the ticket you linked describes another problem. At the moment you cannot inherit the views of another theme, when you create a new theme. This is an issue with which we also have problems. Our plan was to create a whitelabel theme and inherit from it to create new themes for every customer. As a workaround we copy the complete whitelabel theme project for every new theme.
But that's not really related to this issue. Just as a hint, that we are having problems with it.

**Comment by peterjaap** [comment] 2020-08-11 12:59
@NicoWenig27 AFAIK, view inheritance now does work, except the config settings don't (as you mentioned here as well). I've opened another issue about it here; https://github.com/shopware/platform/issues/1227

**Comment by shyim** [comment] 2021-10-14 07:08
They are merged in the newest version.

**Closed as completed by shyim** 2021-10-14 07:08 UTC
