### ISSUE TITLE
.env.local not respected on install

### ISSUE THREAD

**Issue by riconeitzel** [shopware/shopware#1596] opened 2021-01-13 20:56 UTC
**Description**  
I tried to install shopware via composer with shopware/production 6.3.4.1 and created an .env.local file with required information to run bin/console system:setup

Installation failed due to missing _ENV variables.

```
In EnvVarProcessor.php line 171:
                                              
  Environment variable not found: "APP_URL".  
                                       
```

I renamed the file to .env and it worked.

**Possible Solution**  
Verify the presence of .env.{APP_ENV} and .env.local before running the installation.

**Comment by AndreasA** [comment] 2021-01-25 20:35
Personally I think the issue is actually the template as if you check here https://github.com/shopware/production/blob/6.3/public/index.php

and the same goes for the corresponding console file, they use ` (new Dotenv(true))->load($envFile);` intead of the new `(new Dotenv())->bootEnv(dirname(__DIR__).'/.env');` or `(new Dotenv(false))->loadEnv(dirname(__DIR__).'/.env');` (this one defintily exists in 4.4, the other one migh be new in 5.x)

If you have to use it, you could change the corresponding methods yourself in those files.

However, the issue is that the newer Symfony`.env` loading standard will not work correctly with their storefront and admin build scripts and probably also not with the install command and install web page which is probably why it is not used yet.

**Comment by MarcelSchmaeing** [comment] 2024-08-20 13:46
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.

**Closed as not planned by MarcelSchmaeing** 2024-08-20 13:46 UTC
